name: Devops - build and push

on:
  push:
    branches: ['main']
    paths:
      - './Dockerfile'
  workflow_dispatch:
  schedule:
    # Runs every day At 10:00.
    - cron: '0 10 * * 1'

env:
  REGISTRY_IMAGE: djimenezc/devops-tools

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.REGISTRY_IMAGE }}:latest
          cache-to: type=inline
          tags: |
            ${{ env.REGISTRY_IMAGE }}:1.0.0
            ${{ env.REGISTRY_IMAGE }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

